apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeting
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
      - name: greeting
        image: atjapan2015/studyk8s:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 30055
          name: "debug"
---
apiVersion: v1
kind: Service
metadata:
  name: greeting
spec:
  selector:
    app: greeting
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  - name: debug
    protocol: TCP
    port: 30055
    targetPort: 30055
    nodePort: 30055
  type: NodePort
